"""
Blender Demo Constants
---------------------
Centralized constants for Blender demo scripts.
"""

# Render Settings
DEFAULT_RENDER_ENGINE = "CYCLES"
DEFAULT_RESOLUTION_X = 1920
DEFAULT_RESOLUTION_Y = 1080
DEFAULT_RESOLUTION_PERCENTAGE = 100
DEFAULT_SAMPLES = 128
DEFAULT_SAMPLES_PREVIEW = 64
HIGH_QUALITY_SAMPLES = 256
LOW_QUALITY_SAMPLES = 32

# Camera Settings
DEFAULT_CAMERA_LENS = 35
DEFAULT_CAMERA_CLIP_START = 0.1
DEFAULT_CAMERA_CLIP_END = 100
DEFAULT_CAMERA_DISTANCE = 10
DEFAULT_CAMERA_HEIGHT = 5

# Lighting Settings
DEFAULT_KEY_LIGHT_ENERGY = 500
DEFAULT_FILL_LIGHT_ENERGY = 200
DEFAULT_BACK_LIGHT_ENERGY = 300
DEFAULT_SUN_ENERGY = 5
DEFAULT_LIGHT_SIZE = 2

# Material Settings
DEFAULT_METALLIC = 0.0
DEFAULT_ROUGHNESS = 0.5
DEFAULT_GROUND_ROUGHNESS = 0.9  # Ground planes should be rougher/more diffuse
DEFAULT_SPECULAR = 0.5
DEFAULT_TRANSMISSION = 0.0
DEFAULT_IOR = 1.45

# Object Settings
DEFAULT_OBJECT_SIZE = 1.0
DEFAULT_GROUND_PLANE_SIZE = 20

# Colors (RGBA)
COLOR_WHITE = (1.0, 1.0, 1.0, 1.0)
COLOR_BLACK = (0.0, 0.0, 0.0, 1.0)
COLOR_RED = (0.8, 0.2, 0.2, 1.0)
COLOR_GREEN = (0.2, 0.8, 0.2, 1.0)
COLOR_BLUE = (0.2, 0.2, 0.8, 1.0)
COLOR_GRAY = (0.5, 0.5, 0.5, 1.0)
COLOR_DARK_GRAY = (0.2, 0.2, 0.2, 1.0)

# Animation Settings
DEFAULT_FRAME_START = 1
DEFAULT_FRAME_END = 120
DEFAULT_FPS = 24

# File Formats
IMAGE_FORMAT_PNG = "PNG"
IMAGE_FORMAT_JPEG = "JPEG"
IMAGE_FORMAT_TIFF = "TIFF"
IMAGE_FORMAT_EXR = "OPEN_EXR"

# Interpolation Types
INTERPOLATION_BEZIER = "BEZIER"
INTERPOLATION_LINEAR = "LINEAR"
INTERPOLATION_CONSTANT = "CONSTANT"

# Light Types
LIGHT_SETUP_THREE_POINT = "three_point"
LIGHT_SETUP_STUDIO = "studio"
LIGHT_SETUP_OUTDOOR = "outdoor"

# Object Types
OBJECT_TYPE_CUBE = "CUBE"
OBJECT_TYPE_SPHERE = "SPHERE"
OBJECT_TYPE_CYLINDER = "CYLINDER"
OBJECT_TYPE_CONE = "CONE"
OBJECT_TYPE_TORUS = "TORUS"
